### ISSUE TITLE
refactor: 이번 주 피드 백 반영

### ISSUE THREAD

**Issue by yeonise** [second-hand-team-04/second-hand-max-be-a#53]
## To Do

- [x] request에서 User를 생성하는 팩토리 메서드를 추가합니다.
- [ ] regex 패턴과 메세지 관리를 분리합니다.

## Considerations

1. BaseTimeEntity에 `updatedAt` 을 추가할 것인지에 대한 논의가 필요합니다.
2. File signature 관련 논의가 필요합니다.

**Comment by Ojeegu** [comment]
regexg 패턴과 메세지 관리 분리해보려고 했는데 어노테이션은 상수만 값으로 넣을 수 있다고 해서 조금 고민 되네요.
[참고 링크](https://stir.tistory.com/321) 보시고 내일 같이 얘기해봐요!

**Comment by yeonise** [comment]
저희 그럼 코쿼에서 얘기한 것처럼 상수 관리는 하지 않는 거로..! 👌🏻
